;;;; zmq-cffi/package.lisp

(defpackage #:zmq-cffi
  (:use
   #:cl)
  (:local-nicknames
   (#:cffi #:cffi))
  (:export
   #:size-t
   #:uint8-t
   #:zmq-fd-t
   #:uint32-t
   #:uint64-t
   #-WIN32 #:sigset-t
   #:zmq-version-major 
   #:zmq-version-minor 
   #:zmq-version-patch 
   #:zmq-version 
   #:enotsup 
   #:eprotonosupport 
   #:enobufs 
   #:enetdown 
   #:eaddrinuse 
   #:eaddrnotavail 
   #:econnrefused 
   #:einprogress 
   #:enotsock 
   #:emsgsize 
   #:eafnosupport 
   #:enetunreach 
   #:econnaborted 
   #:econnreset 
   #:enotconn 
   #:etimedout 
   #:ehostunreach 
   #:enetreset 
   #:efsm 
   #:enocompatproto 
   #:eterm 
   #:emthread 
   #:zmq-io-threads 
   #:zmq-max-sockets 
   #:zmq-socket-limit 
   #:zmq-thread-priority 
   #:zmq-thread-sched-policy 
   #:zmq-max-msgsz 
   #:zmq-msg-t-size 
   #:zmq-thread-affinity-cpu-add 
   #:zmq-thread-affinity-cpu-remove 
   #:zmq-thread-name-prefix 
   #:zmq-io-threads-dflt 
   #:zmq-max-sockets_dflt 
   #:zmq-thread-priority-dflt 
   #:zmq-thread-sched-policy-dflt 
   #:zmq-pair 
   #:zmq-pub 
   #:zmq-sub 
   #:zmq-req 
   #:zmq-rep 
   #:zmq-dealer 
   #:zmq-router 
   #:zmq-pull 
   #:zmq-push 
   #:zmq-xpub 
   #:zmq-xsub 
   #:zmq-stream 
   #:zmq-affinity 
   #:zmq-routing-id 
   #:zmq-subscribe 
   #:zmq-unsubscribe 
   #:zmq-rate 
   #:zmq-recovery-ivl 
   #:zmq-sndbuf 
   #:zmq-rcvbuf 
   #:zmq-rcvmore 
   #:zmq-fd 
   #:zmq-events 
   #:zmq-type 
   #:zmq-linger 
   #:zmq-reconnect-ivl 
   #:zmq-backlog 
   #:zmq-reconnect-ivl-max 
   #:zmq-maxmsgsize 
   #:zmq-sndhwm 
   #:zmq-rcvhwm 
   #:zmq-multicast-hops 
   #:zmq-rcvtimeo 
   #:zmq-sndtimeo 
   #:zmq-last-endpoint 
   #:zmq-router-mandatory 
   #:zmq-tcp-keepalive 
   #:zmq-tcp-keepalive-cnt 
   #:zmq-tcp-keepalive-idle 
   #:zmq-tcp-keepalive-intvl 
   #:zmq-immediate 
   #:zmq-xpub-verbose 
   #:zmq-router-raw 
   #:zmq-ipv6 
   #:zmq-mechanism 
   #:zmq-plain-server 
   #:zmq-plain-username 
   #:zmq-plain-password 
   #:zmq-curve-server 
   #:zmq-curve-publickey 
   #:zmq-curve-secretkey 
   #:zmq-curve-serverkey 
   #:zmq-probe-router 
   #:zmq-req-correlate 
   #:zmq-req-relaxed 
   #:zmq-conflate 
   #:zmq-zap-domain 
   #:zmq-router-handover 
   #:zmq-tos 
   #:zmq-connect-routing-id 
   #:zmq-gssapi-server 
   #:zmq-gssapi-principal 
   #:zmq-gssapi-service-principal 
   #:zmq-gssapi-plaintext 
   #:zmq-handshake-ivl 
   #:zmq-socks-proxy 
   #:zmq-xpub-nodrop 
   #:zmq-blocky 
   #:zmq-xpub-manual 
   #:zmq-xpub-welcome-msg 
   #:zmq-stream-notify 
   #:zmq-invert-matching 
   #:zmq-heartbeat-ivl 
   #:zmq-heartbeat-ttl 
   #:zmq-heartbeat-timeout 
   #:zmq-xpub-verboser 
   #:zmq-connect-timeout 
   #:zmq-tcp-maxrt 
   #:zmq-thread-safe 
   #:zmq-multicast-maxtpdu 
   #:zmq-vmci-buffer-size 
   #:zmq-vmci-buffer-min-size 
   #:zmq-vmci-buffer-max-size 
   #:zmq-vmci-connect-timeout 
   #:zmq-use-fd 
   #:zmq-gssapi-principal-nametype 
   #:zmq-gssapi-service-principal-nametype 
   #:zmq-bindtodevice 
   #:zmq-more 
   #:zmq-shared 
   #:zmq-dontwait 
   #:zmq-sndmore 
   #:zmq-null 
   #:zmq-plain 
   #:zmq-curve 
   #:zmq-gssapi 
   #:zmq-group-max-length 
   #:zmq-identity 
   #:zmq-connect-rid 
   #:zmq-tcp-accept-filter 
   #:zmq-ipc-filter-pid 
   #:zmq-ipc-filter-uid 
   #:zmq-ipc-filter-gid 
   #:zmq-ipv4only 
   #:zmq-delay-attach-on-connect 
   #:zmq-noblock 
   #:zmq-fail-unroutable 
   #:zmq-router-behavior 
   #:zmq-srcfd 
   #:zmq-gssapi-nt-hostbased 
   #:zmq-gssapi-nt-user-name 
   #:zmq-gssapi-nt-krb5-principal 
   #:zmq-event-connected 
   #:zmq-event-connect-delayed 
   #:zmq-event-connect-retried 
   #:zmq-event-listening 
   #:zmq-event-bind-failed 
   #:zmq-event-accepted 
   #:zmq-event-accept-failed 
   #:zmq-event-closed 
   #:zmq-event-close-failed 
   #:zmq-event-disconnected 
   #:zmq-event-monitor-stopped 
   #:zmq-event-all 
   #:zmq-event-handshake-failed-no-detail 
   #:zmq-event-handshake-succeeded 
   #:zmq-event-handshake-failed-protocol 
   #:zmq-event-handshake-failed-auth 
   #:zmq-protocol-error-zmtp-unspecified 
   #:zmq-protocol-error-zmtp-unexpected-command 
   #:zmq-protocol-error-zmtp-invalid-sequence 
   #:zmq-protocol-error-zmtp-key-exchange 
   #:zmq-protocol-error-zmtp-malformed-command-unspecified 
   #:zmq-protocol-error-zmtp-malformed-command-message 
   #:zmq-protocol-error-zmtp-malformed-command-hello 
   #:zmq-protocol-error-zmtp-malformed-command-initiate 
   #:zmq-protocol-error-zmtp-malformed-command-error 
   #:zmq-protocol-error-zmtp-malformed-command-ready 
   #:zmq-protocol-error-zmtp-malformed-command-welcome 
   #:zmq-protocol-error-zmtp-invalid-metadata 
   #:zmq-protocol-error-zmtp-cryptographic 
   #:zmq-protocol-error-zmtp-mechanism-mismatch 
   #:zmq-protocol-error-zap-unspecified 
   #:zmq-protocol-error-zap-malformed-reply 
   #:zmq-protocol-error-zap-bad-request-id 
   #:zmq-protocol-error-zap-bad-version 
   #:zmq-protocol-error-zap-invalid-status-code 
   #:zmq-protocol-error-zap-invalid-metadata 
   #:zmq-protocol-error-ws-unspecified 
   #:zmq-pollin 
   #:zmq-pollout 
   #:zmq-pollerr 
   #:zmq-pollpri 
   #:zmq-pollitems-dflt 
   #:zmq-has-capabilities 
   #:zmq-streamer 
   #:zmq-forwarder 
   #:zmq-queue 
   #:zmq-server 
   #:zmq-client 
   #:zmq-radio 
   #:zmq-dish 
   #:zmq-gather 
   #:zmq-scatter 
   #:zmq-dgram 
   #:zmq-peer 
   #:zmq-channel 
   #:zmq-zap-enforce-domain 
   #:zmq-loopback-fastpath 
   #:zmq-metadata 
   #:zmq-multicast-loop 
   #:zmq-router-notify 
   #:zmq-xpub-manual-last-value 
   #:zmq-socks-username 
   #:zmq-socks-password 
   #:zmq-in-batch-size 
   #:zmq-out-batch-size 
   #:zmq-wss-key-pem 
   #:zmq-wss-cert-pem 
   #:zmq-wss-trust-pem 
   #:zmq-wss-hostname 
   #:zmq-wss-trust-system 
   #:zmq-only-first-subscribe 
   #:zmq-reconnect-stop 
   #:zmq-hello-msg 
   #:zmq-disconnect-msg 
   #:zmq-priority 
   #:zmq-busy-poll 
   #:zmq-hiccup-msg 
   #:zmq-xsub-verbose-unsubscribe 
   #:zmq-topics-count 
   #:zmq-norm-mode 
   #:zmq-norm-unicast-nack 
   #:zmq-norm-buffer-size 
   #:zmq-norm-segment-size 
   #:zmq-norm-block-size 
   #:zmq-norm-num-parity 
   #:zmq-norm-num-autoparity 
   #:zmq-norm-push 
   #:zmq-norm-fixed 
   #:zmq-norm-cc 
   #:zmq-norm-ccl 
   #:zmq-norm-cce 
   #:zmq-norm-cce-ecnonly 
   #:zmq-reconnect-stop-conn-refused 
   #:zmq-reconnect-stop-handshake-failed 
   #:zmq-reconnect-stop-after-disconnect 
   #:zmq-zero-copy-recv 
   #:zmq-notify-connect 
   #:zmq-notify-disconnect 
   #:zmq-event-pipes-states 
   #:zmq-current-event-version 
   #:zmq-current-event-version-draft 
   #:zmq-event-all-v1 
   #:zmq-event-all-v2
   #:memcpy
   #:libzmq
   #:zmq-errno 
   #:zmq-strerror 
   #:zmq-version 
   #:zmq-ctx-new 
   #:zmq-ctx-term 
   #:zmq-ctx-shutdown 
   #:zmq-ctx-set 
   #:zmq-ctx-get 
   #:zmq-init 
   #:zmq-term 
   #:zmq-ctx-destroy
   #:zmq-msg-t
   #:zmq-free-fn
   #:zmq-msg-init 
   #:zmq-msg-init-size 
   #:zmq-msg-init-data 
   #:zmq-msg-send 
   #:zmq-msg-recv 
   #:zmq-msg-close 
   #:zmq-msg-move 
   #:zmq-msg-copy 
   #:zmq-msg-data 
   #:zmq-msg-size 
   #:zmq-msg-more 
   #:zmq-msg-get 
   #:zmq-msg-set 
   #:zmq-msg-gets 
   #:zmq-socket 
   #:zmq-close 
   #:zmq-setsockopt
   #:zmq-getsockopt 
   #:zmq-bind 
   #:zmq-connect 
   #:zmq-unbind 
   #:zmq-disconnect 
   #:zmq-send 
   #:zmq-send-const 
   #:zmq-recv 
   #:zmq-socket-monitor
   #:zmq-pollitem-t
   #:socket
   #:fd
   #:events
   #:revents
   #:zmq-poll 
   #:zmq-proxy 
   #:zmq-proxy-steerable 
   #:zmq-has 
   #:zmq-device 
   #:zmq-sendmsg 
   #:zmq-recvmsg 
   #:zmq-sendiov 
   #:zmq-recviov 
   #:zmq-z85-encode 
   #:zmq-z85-decode 
   #:zmq-curve-keypair 
   #:zmq-curve-public 
   #:zmq-atomic-counter-new 
   #:zmq-atomic-counter-set 
   #:zmq-atomic-counter-inc 
   #:zmq-atomic-counter-dec 
   #:zmq-atomic-counter-value 
   #:zmq-atomic-counter-destroy 
   #:zmq-timers-new 
   #:zmq-timers-destroy 
   #:zmq-timers-add 
   #:zmq-timers-cancel 
   #:zmq-timers-set-interval 
   #:zmq-timers-reset 
   #:zmq-timers-timeout 
   #:zmq-timers-execute 
   #:zmq-stopwatch-start 
   #:zmq-stopwatch-intermediate 
   #:zmq-stopwatch-stop 
   #:zmq-sleep 
   #:zmq-threadstart 
   #:zmq-threadclose 
   #:zmq-ctx-set-ext 
   #:zmq-ctx-get-ext 
   #:zmq-join 
   #:zmq-leave 
   #:zmq-connect-peer 
   #:zmq-msg-set-routing-id 
   #:zmq-msg-routing-id 
   #:zmq-msg-set-group 
   #:zmq-msg-group 
   #:zmq-msg-init-buffer 
   #:zmq-poller-new 
   #:zmq-poller-destroy 
   #:zmq-poller-size 
   #:zmq-poller-add 
   #:zmq-poller-modify 
   #:zmq-poller-remove 
   #:zmq-poller-wait 
   #:zmq-poller-wait-all 
   #:zmq-poller-fd 
   #:zmq-poller-add-fd 
   #:zmq-poller-modify-fd 
   #:zmq-poller-remove-fd 
   #:zmq-socket-get-peer-state 
   #:zmq-socket-monitor-versioned 
   #:zmq-socket-monitor-pipes-stats 
   #:zmq-ppoll))

