;;;; zmq/package.lisp

(defpackage #:zmq
  (:use
   #:coalton
   #:coalton-prelude)
  (:import-from
   #:coalton-library/result
   #:ok?)
  (:import-from
   #:coalton-library/experimental/loops
   #:dolist)
  (:local-nicknames
   (#:array #:coalton-library/lisparray)
   (#:cffi #:cffi)
   (#:char #:coalton-library/char)
   (#:list #:coalton-library/list)
   (#:string #:coalton-library/string)
   (#:zmq-cffi #:zmq-cffi))
  (:export
   #:Pointer
   #:free
   #:Buffer
   #:Callback
   #:Int
   #:Long
   #:Short
   #:bitfield-member?
   #:SizeT
   #:UInt8T
   #:ZMQFDT
   #:UInt32T
   #:UInt64T
   #-WIN32 #:SigsetT
   #:Version
   #:+zmq-version+
   #:Context
   #:Socket
   #:Message
   #:new-message
   #:Pollitem
   #:new-pollitem
   #:new-pollitem-array
   #:set-pollitem-slots
   #:pollitem-socket
   #:pollitem-fd
   #:pollitem-events
   #:pollitem-revents
   #:ZMQError
   #:enotsup
   #:eprotonosupport
   #:enobufs
   #:enetdown
   #:eaddrinuse
   #:eaddrnotavail
   #:econnrefused
   #:einprogress
   #:enotsock
   #:emsgsize
   #:eafnosupport
   #:enetunreach
   #:econnaborted
   #:econnreset
   #:enotconn
   #:etimedout
   #:ehostunreach
   #:enetreset
   #:efsm
   #:enocompatproto
   #:eterm
   #:emthread
   #:ContextOption
   #:zmq-io-threads 
   #:zmq-max-sockets 
   #:zmq-socket-limit 
   #:zmq-thread-priority 
   #:zmq-thread-sched-policy 
   #:zmq-max-msgsz 
   #:zmq-msg-t-size 
   #:zmq-thread-affinity-cpu-add 
   #:zmq-thread-affinity-cpu-remove 
   #:zmq-thread-name-prefix 
   #:zmq-io-threads-dflt 
   #:zmq-max-sockets_dflt 
   #:zmq-thread-priority-dflt 
   #:zmq-thread-sched-policy-dflt
   #:SocketType
   #:zmq-pair
   #:zmq-pub
   #:zmq-sub
   #:zmq-req
   #:zmq-rep
   #:zmq-dealer
   #:zmq-router
   #:zmq-pull
   #:zmq-push
   #:zmq-xpub
   #:zmq-xsub
   #:SocketOption
   #:zmq-affinity 
   #:zmq-routing-id 
   #:zmq-subscribe 
   #:zmq-unsubscribe 
   #:zmq-rate 
   #:zmq-recovery-ivl 
   #:zmq-sndbuf 
   #:zmq-rcvbuf 
   #:zmq-rcvmore 
   #:zmq-fd 
   #:zmq-events 
   #:zmq-type 
   #:zmq-linger 
   #:zmq-reconnect-ivl 
   #:zmq-backlog 
   #:zmq-reconnect-ivl-max 
   #:zmq-maxmsgsize 
   #:zmq-sndhwm 
   #:zmq-rcvhwm 
   #:zmq-multicast-hops 
   #:zmq-rcvtimeo 
   #:zmq-sndtimeo 
   #:zmq-last-endpoint 
   #:zmq-router-mandatory 
   #:zmq-tcp-keepalive 
   #:zmq-tcp-keepalive-cnt 
   #:zmq-tcp-keepalive-idle 
   #:zmq-tcp-keepalive-intvl 
   #:zmq-immediate 
   #:zmq-xpub-verbose 
   #:zmq-router-raw 
   #:zmq-ipv6 
   #:zmq-mechanism 
   #:zmq-plain-server 
   #:zmq-plain-username 
   #:zmq-plain-password 
   #:zmq-curve-server 
   #:zmq-curve-publickey 
   #:zmq-curve-secretkey 
   #:zmq-curve-serverkey 
   #:zmq-probe-router 
   #:zmq-req-correlate 
   #:zmq-req-relaxed 
   #:zmq-conflate 
   #:zmq-zap-domain 
   #:zmq-router-handover 
   #:zmq-tos 
   #:zmq-connect-routing-id 
   #:zmq-gssapi-server 
   #:zmq-gssapi-principal 
   #:zmq-gssapi-service-principal 
   #:zmq-gssapi-plaintext 
   #:zmq-handshake-ivl 
   #:zmq-socks-proxy 
   #:zmq-xpub-nodrop 
   #:zmq-blocky 
   #:zmq-xpub-manual 
   #:zmq-xpub-welcome-msg 
   #:zmq-stream-notify 
   #:zmq-invert-matching 
   #:zmq-heartbeat-ivl 
   #:zmq-heartbeat-ttl 
   #:zmq-heartbeat-timeout 
   #:zmq-xpub-verboser 
   #:zmq-connect-timeout 
   #:zmq-tcp-maxrt 
   #:zmq-thread-safe 
   #:zmq-multicast-maxtpdu 
   #:zmq-vmci-buffer-size 
   #:zmq-vmci-buffer-min-size 
   #:zmq-vmci-buffer-max-size 
   #:zmq-vmci-connect-timeout 
   #:zmq-use-fd 
   #:zmq-gssapi-principal-nametype 
   #:zmq-gssapi-service-principal-nametype 
   #:zmq-bindtodevice
   #:MessageOption
   #:zmq-more
   #:zmq-shared
   #:SendRecvFlag
   #:zmq-dontwait
   #:zmq-sndmore
   #:SecurityMechanism
   #:zmq-null
   #:zmq-plain
   #:zmq-curve
   #:zmq-gssapi
   #:RadioDishProtocol
   #:zmq-group-max-length
   #:SocketTransportEvent
   #:zmq-event-connected
   #:zmq-event-connect-delayed
   #:zmq-event-connect-retried
   #:zmq-event-listening
   #:zmq-event-bind-failed
   #:zmq-event-accepted
   #:zmq-event-accept-failed
   #:zmq-event-closed
   #:zmq-event-close-failed
   #:zmq-event-disconnected
   #:zmq-event-monitor-stopped
   #:zmq-event-all
   #:zmq-event-handshake-failed-no-detail
   #:zmq-event-handshake-succeeded
   #:zmq-event-handshake-failed-protocol
   #:zmq-event-handshake-failed-auth
   #:ProtocolError
   #:PollOption
   #:zmq-pollin
   #:zmq-pollout
   #:zmq-pollerr
   #:zmq-pollpri
   #:load-libzmq
   #:zmq-errno
   #:zmq-strerror
   #:zmq-version
   #:zmq-ctx-new
   #:zmq-ctx-term
   #:zmq-ctx-shutdown
   #:zmq-ctx-set
   #:zmq-ctx-get
   #:zmq-init
   #:zmq-term
   #:zmq-ctx-destroy
   #:zmq-msg-init
   #:zmq-msg-init-size
   #:zmq-msg-init-data
   #:zmq-msg-send
   #:zmq-msg-recv
   #:zmq-msg-close
   #:zmq-msg-move
   #:zmq-msg-copy
   #:zmq-msg-data
   #:zmq-msg-size
   #:zmq-msg-more
   #:zmq-msg-get
   #:zmq-msg-set
   #:zmq-msg-gets
   #:zmq-socket
   #:zmq-close
   #:zmq-setsockopt
   #:zmq-getsockopt
   #:zmq-bind
   #:zmq-connect
   #:zmq-unbind
   #:zmq-disconnect
   #:zmq-send
   #:zmq-send-const
   #:zmq-recv
   #:zmq-socket-monitor
   #:zmq-poll

   ;; EXT
   #:finalize-message
   #:send
   #:recv
   #:sendmore
   #:recvnow
   #:recvall
   #:subscribe
   #:unsubscribe
   ))

